name: app_ai
description: "A professional AI Chat & Image Generation App."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  get: ^4.6.6
  
  # Local Storage
  get_storage: ^2.1.1
  
  # Networking
  http: ^1.2.0
  
  # UI/Text Rendering
  flutter_markdown: ^0.7.2
  google_fonts: ^6.2.1
  
  # Voice & Utilities
  speech_to_text: ^7.3.0
  permission_handler: ^11.3.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
